version: '3'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: unless-stopped
    # hostname: 'coiot.duckdns.org'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://coiot.duckdns.org:2225'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['initial_root_password'] = 'superiot'
    ports:
      - '2225:2225'
      # - '443:443'
      - '2224:22'
    volumes:
      - ./gitlab-data/config:/etc/gitlab
      - ./gitlab-data/logs:/var/log/gitlab
      - ./gitlab-data/data:/var/opt/gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    depends_on:
      - web

# volumes:
  # gitlab-data:
