version: '3.4'
services:
  nginx:
    network_mode: host
    image: nginx:1.15-alpine
    restart: unless-stopped
    # ports:
    #   - "80:80"
    #   - "443:443"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d:ro
      - ./nginx/certbot/conf:/etc/letsencrypt:ro
      - ./nginx/certbot/www:/var/www/certbot:ro

  certbot:
    image: certbot/certbot
    volumes:
        - ./nginx/certbot/conf:/etc/letsencrypt
        - ./nginx/certbot/www:/var/www/certbot
    command: --help
